#!/usr/bin/python3

import multiprocessing as mp

class cls:
    def __init__(self):
        self.var = "A"
    def set_var(self, var):
        self.var = var

def foo(qIn, qOut, cls):
    while (True):
        newVar = qIn.get()
        print(newVar)
        print("Got %s " % newVar)
        if newVar is "None":
            print "Exiting Bro"
            qOut.put("EXITING PROGRAM")
            return
        qOut.put(newVar)

if __name__ == '__main__':
    mp.set_start_method('spawn')

    myClass = cls()
    qIn = mp.Queue()
    qOut = mp.Queue()

    p = mp.Process(target=foo, args=(qIn, qOut, myClass))
    
    p.start()
    
    qIn.put("Hello")
    print (qOut.get())
    
    qIn.put("Goodbye")
    print(qOut.get())
    
    qIn.put("None")
    qOut.get()

    p.join()
